const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Plugins.HTMLElement,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Plugins.TextBox,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Tilemap,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{小玉: 0},
	{閃爍: 0},
	{毒蟒red: 0},
	{對話框: 0},
	{HTML元素: 0},
	{Sprite: 0},
	{藥屋森林: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Text: 0},
	{鍵盤: 0},
	{Sprite6: 0},
	{bear: 0},
	{bear2: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{位圖字體: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{位圖字體2: 0},
	{文本框: 0},
	{Text2: 0},
	{Text3: 0},
	{Text4: 0},
	{滑鼠: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{音頻: 0},
	{music: 0},
	{Tilemap: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{Sprite35: 0},
	{Sprite38: 0},
	{Sprite33: 0},
	{changeNum: 0}
];

self.InstanceType = {
	小玉: class extends self.ISpriteInstance {},
	毒蟒red: class extends self.ISpriteInstance {},
	對話框: class extends self.ISpriteInstance {},
	HTML元素: class extends self.IHTMLElementInstance {},
	Sprite: class extends self.ISpriteInstance {},
	藥屋森林: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	鍵盤: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	bear: class extends self.ISpriteInstance {},
	bear2: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	位圖字體: class extends self.ISpriteFontInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	位圖字體2: class extends self.ISpriteFontInstance {},
	文本框: class extends self.ITextInputInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	滑鼠: class extends self.IInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	音頻: class extends self.IInstance {},
	music: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {}
}